// PDF generation using @react-pdf/renderer
// This module is used server-side in the export API route

import { formatTime } from '@/lib/utils';

interface PdfData {
  meeting: {
    title: string | null;
    created_at: string;
    audio_duration_seconds: number | null;
  };
  summary: {
    summary_text: string;
    summary_text_zh?: string | null;
    key_decisions: Array<{ text: string; speaker?: string }>;
    action_items: Array<{
      text: string;
      assignee?: string;
      due_date?: string;
      status?: string;
    }>;
    topics: Array<{ name: string }>;
    sentiment?: string | null;
  };
  segments: Array<{
    speaker_label: string | null;
    start_time_ms: number;
    text: string;
  }>;
  speakerMap: Record<string, string>;
}

export function generatePdfHtml(data: PdfData): string {
  const { meeting, summary, segments, speakerMap } = data;

  const getSpeaker = (label: string | null) =>
    label ? speakerMap[label] || label : 'Unknown';

  const date = new Date(meeting.created_at).toLocaleDateString('en-HK', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  h2 { font-size: 18px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin-top: 32px; color: #1e40af; }
  .summary { font-size: 15px; }
  .summary-zh { color: #666; font-size: 14px; margin-top: 8px; }
  .action-item { display: flex; align-items: flex-start; gap: 8px; margin-bottom: 8px; }
  .checkbox { width: 14px; height: 14px; border: 2px solid #d1d5db; border-radius: 3px; flex-shrink: 0; margin-top: 3px; }
  .checkbox.done { background: #22c55e; border-color: #22c55e; }
  .assignee { color: #2563eb; font-size: 12px; background: #eff6ff; padding: 2px 8px; border-radius: 10px; }
  .decision { margin-bottom: 8px; padding-left: 16px; border-left: 3px solid #2563eb; }
  .topics { display: flex; flex-wrap: wrap; gap: 6px; }
  .topic { background: #eff6ff; color: #1e40af; padding: 4px 12px; border-radius: 16px; font-size: 13px; }
  .segment { margin-bottom: 8px; font-size: 14px; }
  .segment .speaker { font-weight: 600; color: #2563eb; }
  .segment .time { color: #9ca3af; font-size: 12px; margin-left: 8px; }
  .segment .text { margin-top: 2px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
</style>
</head>
<body>

<h1>${meeting.title || 'Untitled Meeting'}</h1>
<div class="meta">${date}${meeting.audio_duration_seconds ? ` &bull; ${Math.round(meeting.audio_duration_seconds / 60)} min` : ''}</div>

<h2>Summary</h2>
<div class="summary">${summary.summary_text}</div>
${summary.summary_text_zh ? `<div class="summary-zh">${summary.summary_text_zh}</div>` : ''}

${
  summary.action_items.length > 0
    ? `<h2>Action Items</h2>
${summary.action_items
  .map(
    (item) => `<div class="action-item">
  <div class="checkbox ${item.status === 'completed' ? 'done' : ''}"></div>
  <div>
    <span>${item.text}</span>
    ${item.assignee ? `<span class="assignee">${item.assignee}</span>` : ''}
    ${item.due_date ? `<span style="color:#666;font-size:12px;margin-left:8px">Due: ${item.due_date}</span>` : ''}
  </div>
</div>`
  )
  .join('\n')}`
    : ''
}

${
  summary.key_decisions.length > 0
    ? `<h2>Key Decisions</h2>
${summary.key_decisions.map((d) => `<div class="decision">${d.text}</div>`).join('\n')}`
    : ''
}

${
  summary.topics.length > 0
    ? `<h2>Topics</h2>
<div class="topics">${summary.topics.map((t) => `<span class="topic">${t.name}</span>`).join('')}</div>`
    : ''
}

<h2>Full Transcript</h2>
${segments
  .map(
    (s) => `<div class="segment">
  <span class="speaker">${getSpeaker(s.speaker_label)}</span>
  <span class="time">${formatTime(s.start_time_ms)}</span>
  <div class="text">${s.text}</div>
</div>`
  )
  .join('\n')}

<div class="footer">Generated by MeetNotes HK</div>

</body>
</html>`;
}
